New branch
ClintonWeeYuan/matchmaking_homework pull request #1
Opened 2021-02-25 04:36 UTC by ClintonWeeYuan

2021-02-25 05:46 UTC, jonathanmcc requested changes

2021-02-25 05:46 UTC, jonathanmcc commented on matchmake.js
> +    const advisor_keys = Object.keys(advisor);
advisor_keys was declared but never used

2021-02-25 05:46 UTC, jonathanmcc commented on matchmake.js
> +      if (applicant[key] === advisor[key]){
With this logic, if an applicant has `{"postgradUni":"cambridge"}` and the advisor has `{"postgradUni":"cambridge","postgradUniPrev":"cambridge"}`, the match will only gain score once. The correct result should gain the matchmaking score twice.

2021-02-26 05:23 UTC, ClintonWeeYuan commented on matchmake.js
> +    const advisor_keys = Object.keys(advisor);
Noted with thanks! I realised I didn't need it halfway through coding, but forgot to remove the variable

2021-02-26 05:23 UTC, ClintonWeeYuan commented on matchmake.js
> +      if (applicant[key] === advisor[key]){
Oh, I forgot about that situation. Thanks for pointing it out.

2021-03-12 23:10 UTC, merged